# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-10 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0007_auto_20180810_0700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='profilepicture',
        ),
        migrations.AddField(
            model_name='categories',
            name='picture',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
