# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-10 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0008_auto_20180810_0702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='picture',
        ),
        migrations.AddField(
            model_name='categories',
            name='profilepicture',
            field=models.ImageField(blank=True, upload_to='png/'),
        ),
    ]
